blog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView
from . import views

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
]

django_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from users import views as user_views
from django.urls import path, include
from django.conf import settings

# serving media files in DEBUG=FALSE mode, not appropriate for production
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', user_views.logout_view, name='logout'), # using a custom logout function
    #path('logout/', auth_views.LogoutView.as_view(template_name='users/login.html'), name='logout'),
    path('', include('blog.urls')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), # serving media files in DEBUG=FALSE mode
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from PIL import Image


# defining a database table for posts
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now) # recording the timestamp when a new entry is created
    author = models.ForeignKey(User, on_delete=models.CASCADE) # ForeignKey defines a "many-to-one relationship"
    image = models.ImageField(default='',upload_to='images',blank=True,null=True)
    audio = models.FileField(default='',upload_to='audio',blank=True,null=True)

    def __str__(self):
        return self.title

    # defining a URL for a new entry
    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})

# model names should be singular, for example, Post, because they represent a single object
# fields should be written in lowercase and with underscores
# The __str__ method defines a human-readable representation of the model in the Django admin site
# CASCADE defines that when a user is deleted, all his/her entries are deleted as well

blog/forms.py
from django import forms
from django.forms import ModelForm
from .models import Post
from django.core.exceptions import ValidationError


# creating a form for custom validation
class CreateViewForm(forms.ModelForm):

    title = forms.CharField(required=False) # defining the field as not required
    image = forms.ImageField(required=False)
    audio = forms.FileField(required=False)

    # Meta class is there for defining and altering various metadata features
    class Meta:
        model = Post
        fields = ['title','content','date_posted','image','audio']

    def clean(self): # validation function
        cleaned_data = super(CreateViewForm, self).clean()

        input_field_1 = cleaned_data.get('title') # getting input from the title field
        input_field_2 = cleaned_data.get('content') # getting input from the content field

        if input_field_1 is not None and input_field_2 is not None:
            if len(input_field_2)<3:
                # self.add_error(None, ValidationError('The title should be different')) # non-field error
                self.add_error('content', ValidationError('The message is too short')) # title field error

#   renaming uploaded images
#   def image_file_name(instance, filename):
#       ext = filename.split('.')[-1]
#       filename = "%s_%s.%s" % (instance.date_posted, instance.title, ext) # %s correspond to instances to pass to the new file name
#       return os.path.join('images', filename)


class UpdateViewForm(forms.ModelForm):

    title = forms.CharField(required=False)
    image = forms.ImageField(required=False)
    image_clear = forms.BooleanField(required=False)
    audio = forms.FileField(required=False)
    audio_clear = forms.FileField(required=False)

    class Meta:
        model = Post
        fields = ['title','content','date_posted','image','audio']

    def clean(self):
        cleaned_data = super(UpdateViewForm, self).clean()

        input_field_1 = cleaned_data.get('title')
        input_field_2 = cleaned_data.get('content')
        input_field_3 = cleaned_data.get('date_posted')

        if input_field_1 is not None and input_field_2 is not None:
            if len(input_field_2)<3:
                self.add_error('content', ValidationError('The message is too short'))

blog/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from .forms import CreateViewForm, UpdateViewForm

# enabling case-insensitive search in MySQL databases
from django.db.models import Q, TextField
from django.db.models.functions import Lower
TextField.register_lookup(Lower, "lower")


# if users are allowed to view anyone's posts, not only theirs, then leave this and the next class uncommented
class PostListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'blog/home.html'
    context_object_name = 'posts' # the name of a context variable with the queryset results
    ordering = ['-date_posted']
    paginate_by = 20

    # modifying the function for returning posts
    def get_queryset(self):
        # if there is a search query in the URL parameter, then use it to filter the results
        search_query = self.request.GET.get('search', '')
        # using Q for case-insensitive search in a MySQL database
        queryset = Post.objects.filter(Q(content__lower__contains=search_query)).order_by('-date_posted')
        return queryset


class PostDetailView(LoginRequiredMixin, DetailView):
    model = Post


# if users are allowed to view only their own posts, not anyone else's, then leave this and the next class uncommented
# class PostListView(LoginRequiredMixin, ListView):
#     model = Post
#     template_name = 'blog/home.html'
#     context_object_name = 'posts' # the name of a context variable with the queryset results
#     ordering = ['-date_posted']
#     paginate_by = 20
#
#     # modifying the function for returning posts
#     def get_queryset(self):
#         # if there is a search query in the URL parameter, then use it to filter the results
#         search_query = self.request.GET.get('search', '')
#         # using Q for case-insensitive search in a MySQL database
#         # filtering for posts where the user is the author
#         queryset = Post.objects.filter(Q(content__lower__contains=search_query)).filter(author_id=self.request.user.id).order_by('-date_posted')
#         return queryset
#
# class PostDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
#     model = Post
#
#     def test_func(self):
#         post = self.get_object()
#         if self.request.user == post.author:
#             return True
#         return False


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = CreateViewForm # making the class use an existing form with pre-defined validation rules
    template_name = 'blog/post_create.html'
    success_url = '/'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


# if users are allowed to update or delete anyone's posts, not only theirs, then leave this and the next class uncommented
class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    template_name = 'blog/post_update.html'
    form_class = UpdateViewForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = '/'
    template_name = 'blog/post_delete.html'


# if users are allowed to update or delete only their own posts, then leave this and the next class uncommented
# class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
#     model = Post
#     template_name = 'blog/post_update.html'
#     form_class = UpdateViewForm
#
#     def form_valid(self, form):
#         form.instance.author = self.request.user
#         return super().form_valid(form)
#
#     def test_func(self):
#         post = self.get_object()
#         if self.request.user == post.author:
#             return True
#         return False
#
#
# class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
#     model = Post
#     success_url = '/'
#     template_name = 'blog/post_delete.html'
#
#     def test_func(self):
#         post = self.get_object()
#         if self.request.user == post.author:
#             return True
#         return False


# defining actions when the CSRF error occurs
# the reason parameter here is optional and will only be displayed in logs
def csrf_failure(request, reason=""):
    current_page = request.path
    # iterating through all the pages that contain forms where the user can potentially encounter the CSRF error
    # and calling respective functions again
    try:
        if '/post/new' in current_page:
            return PostCreateView.as_view()(request)
        elif '/update' in current_page:
            return PostUpdateView.as_view()(request)
        elif '/delete' in current_page:
            return PostDeleteView.as_view()(request)
        # redirect to the homepage in any other case, e.g. after login
        else:
            return HttpResponseRedirect('/')
    # if there was any error in calling the respective function, then redirect to the homepage
    except:
        return HttpResponseRedirect('/')

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

<title>Notes</title>
<link rel="shortcut icon" href="{% static 'blog/img/favicon.png' %}" type="image/x-icon">

<!-- Meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- JavaScript files -->
<script src="{% static 'blog/js/moment.min.js' %}"></script>
<script src="{% static 'blog/js/jquery-2.1.1.min.js' %}"></script>
<script src="{% static 'blog/js/bootstrap-datetimepicker.min.js' %}"></script>

<!-- CSS files -->
<link rel="stylesheet" href="{% static 'blog/css/bootstrap-datetimepicker.min.css' %}">
<link rel="stylesheet" href="{% static 'blog/css/modified-bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'blog/css/main.css' %}">

</head>
<body style="background-color:paleturquoise">

<!-- Showing vertical navigation, if the user is logged in -->
{% if user.is_authenticated and 'register' not in request.path and 'login' not in request.path %}

  <div style="background-color:#ebebeb;" class="vertical_nav">
    <a href="{% url 'blog-home' %}">
      <img src="{% static 'blog/img/home.png' %}" style="top:30px;margin-left:20px;">
    </a>
    <a href="{% url 'post-create' %}">
      <button class="nav_button" style="top:110px;margin-left:20px;height:30px;padding:0px;">
        <span>+</span>
      </button>
    </a>
    <a href="{% url 'logout' %}">
      <img src="{% static 'blog/img/logout.png' %}" style="top:190px;margin-left:22.5px;">
    </a>
  </div>

{% endif %}

<div class="container">
  <div {% if 'login' in request.path or 'logout' in request.path or 'register' in request.path %} class="row justify-content-center" {% else %} class="row justify-content-start" {% endif %}>

    <!-- Notifications -->
    {% if message %}
    <div {% if 'logout' in request.path %} class="alert alert-{{ tag }} col-12 col-sm-7 col-md-12 col-lg-12" {% else %} class="alert alert-{{ tag }} col-12" {% endif %} style="margin-bottom:20px;margin-top:-25px;">
      {{ message }}
    </div>
    {% elif request.GET.account == 'success' %}
    <div class="alert alert-success col-12" style="margin-bottom:60px;margin-top:-25px;">
      Your account has been successfully created!
    </div>
    {% endif %}

    <!-- Main content -->
    {% block content %}
    {% endblock %}

  </div>
</div>

</body>
</html>

blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}

<!-- Search form -->
<!-- Display the search form only if there are posts to search in -->
{% if posts or request.GET.search %}
<div id="inputHomepage" style="background-color:white;">
  <form action="" method="get">
    <input type="text" id="searchFieldHomepage" name="search" placeholder="Search" value="{{ request.GET.search }}">
    <button type="submit" value="Search" id="searchButtonHomepage">
      <div>
        <img src="{% static 'blog/img/search.png' %}">
      </div>
    </button>
  </form>
</div>
{% endif %}

<div class="col-12 main_content">
  <!-- Posts -->
  {% if posts %}
    {% for post in posts %}
      <article>
        <div style="background-color:whitesmoke">
          <div class="article-datetime">
            <p>{{ post.date_posted|date:"F j, Y, H:i" }}</p>
          </div>
          <div class="article-headline">
            <a class="article-title" href="{% url 'post-detail' post.id %}">
              {% if post.title %}{{post.title}}{% else %}{{ post.date_posted|date:"F j, Y, H:i" }}{% endif %}
            </a>
          </div>
          <p class="article-content">{{ post.content }}</p>
          {% if post.image %}<img src="{{ post.image.url}}" class="imageMain">{% endif %}
          {% if post.audio %}<audio controls><source src="{{ post.audio.url}}" type="audio/mpeg"></audio>{% endif %}
        </div>
      </article>
    {% endfor %}

    <!-- Pagination -->
    {% if is_paginated %}

      <div class="pagination">
        {% if page_obj.has_previous %}
        {% if page_obj.number > 2 %}
        <a class="button rounded_button opacity_button" {% if request.GET.query %} href="?page=1&search={{ request.GET.search }}" {% else %} href="?page=1" {% endif %}>
          <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-left" fill="currentColor" xmlns="http://www.w3.org/2000/svg" style="font-size:20px;vertical-align:middle;">
            <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
          </svg>
          <span style="padding-left:3px;">First page</span>
        </a>
        {% endif %}
        <a class="button rounded_button secondary_button" {% if request.GET.query %} href="?page={{ page_obj.previous_page_number }}&search={{ request.GET.search }}" {% else %} href="?page={{ page_obj.previous_page_number }}" {% endif %}>
          <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-left" fill="currentColor" xmlns="http://www.w3.org/2000/svg" style="font-size:20px;vertical-align:middle;">
            <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
          </svg>
          <span style="padding-left:3px;">Previous page</span>
        </a>
        {% endif %}
        {% if page_obj.has_next %}
        <a class="button rounded_button secondary_button" {% if request.GET.query %} href="?page={{ page_obj.next_page_number }}&search={{ request.GET.search }}" {% else %} href="?page={{ page_obj.next_page_number }}" {% endif %}>
          <span style="padding-right:3px;">Next page</span>
          <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-right" fill="currentColor" xmlns="http://www.w3.org/2000/svg" style="font-size:20px;vertical-align:middle;">
            <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"/>
          </svg>
        </a>
        <a class="button rounded_button opacity_button" {% if request.GET.query %} href="?page={{ page_obj.paginator.num_pages }}&search={{ request.GET.search }}" {% else %} href="?page={{ page_obj.paginator.num_pages }}" {% endif %}>
          <span style="padding-right:-3px;">Last page</span>
          <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-right" fill="currentColor" xmlns="http://www.w3.org/2000/svg" style="font-size:20px;vertical-align:middle;">
            <path fill-rule="evenodd" d="M10.146 4.646a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L12.793 8l-2.647-2.646a.5.5 0 0 1 0-.708z"/>
            <path fill-rule="evenodd" d="M2 8a.5.5 0 0 1 .5-.5H13a.5.5 0 0 1 0 1H2.5A.5.5 0 0 1 2 8z"/>
          </svg>
        </a>
        {% endif %}
      </div>
    {% endif %}

  {% else %}
    {% if request.GET.search %}
      <p class="no_posts">No posts were found</p>
    {% else %}
      <p class="no_posts" style="margin-top:-40px;">No posts yet</p>
    {% endif %}
  {% endif %}
</div>
{% endblock content %}

blog/templates/blog/post_create.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}

<!-- A popup for date and time selection -->
<script>
  $(function () {
    $('#id_date_posted').datetimepicker({
    format: 'YYYY-MM-DD HH:mm:ss',
    //debug:true,
    icons: {
      time: "icon_time",
      date: "icon_date",
      up: "icon_up",
      down: "icon_down",
      next: "icon_right",
      previous: "icon_left"
    }
  });
 });
</script>

<div class="col-12" style="padding:0px; background-color: yellow">
  <div class="content-section" style="background-color:salmon;">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="article-form">

        {% if form.non_field_errors %}
          <div class="alert alert-danger">
            {% for error in form.non_field_errors %}
              {{ error }}
            {% endfor %}
          </div>
        {% endif %}

        <div class="form-type" style="background-color :yellow;">Create New</div>

        <!-- If the form was already submitted -->
        {% if form.is_bound %}

        {% if form.title.errors %}
          <input name="title" type="text" class="is-invalid" id="id_title" value="{{ form.title.value|default_if_none:'' }}" placeholder="Title" style="margin-top:10px;">
          {% for error in form.title.errors %}
            <div class="invalid-feedback">
              {{ error }}
            </div>
          {% endfor %}
        {% else %}
          <input name="title" type="text" class="is-valid" id="id_title" value="{{ form.title.value|default_if_none:'' }}" placeholder="Title" style="margin-top:10px;">
        {% endif %}

        {% if form.content.errors %}
          <textarea name="content" cols="40" rows="5" class="textarea is-invalid" required id="id_content" value="" placeholder="Message (required)" style="margin-top:20px;">{{ form.content.value|default_if_none:'' }}</textarea>
          {% for error in form.content.errors %}
            <div class="invalid-feedback">
              {{ error }}
            </div>
          {% endfor %}
        {% else %}
          <textarea name="content" cols="40" rows="5" class="textarea is-valid" required id="id_content" value="" placeholder="Message" style="margin-top:20px;">{{ form.content.value|default_if_none:'' }}</textarea>
        {% endif %}

        {% if form.date_posted.errors %}
          <input name="date_posted" type="text" class="is-invalid" id="id_date_posted" value="{{ form.date_posted.value }}" style="margin-top:20px;">
          {% for error in form.date_posted.errors %}
            <div class="invalid-feedback">
              {{ error }}
            </div>
          {% endfor %}
        {% else %}
          <input name="date_posted" type="text" class="is-valid" id="id_date_posted" value="{{ form.date_posted.value }}" style="margin-top:20px;">
        {% endif %}

        <label class="fileContainer" ondragover="dragOver(event,this)" ondragleave="leaveDrop(this)" ondrop="onDrop(event,this)" style="margin-top:20px;">
          <div style="overflow:hidden;text-align:center;">
            <div class="dragDropIcon">
              <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-card-image" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M14.5 3h-13a.5.5 0 0 0-.5.5v9c0 .013 0 .027.002.04V12l2.646-2.354a.5.5 0 0 1 .63-.062l2.66 1.773 3.71-3.71a.5.5 0 0 1 .577-.094L15 9.499V3.5a.5.5 0 0 0-.5-.5zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13zm4.502 3.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
              </svg>
            </div>
            <div class="fileContainerFileName fileName" ondrop="onDrop(event)"><span style="color:rgb(154, 160, 165);">Drag and drop an image here (optional)</span></div>
            <div class="fileContainerFileName fileNameDrop" ondrop="onDrop(event)" style="display:none;"><span style="color:rgb(73,80,87);">Drop it</span></div>
          </div>
          <input accept="image/*" name="image" id="id_image" onchange="fileContainerChangeFile(event,this)" style="margin-top:25px;" type="file"/>
        </label>
        <input type="checkbox" name="image-clear" id="image-clear_id" style="display:none;">

        {% if form.image.errors %}
          {% for error in form.image.errors %}
            <div class="invalid-feedback">
              {{ error }}
            </div>
          {% endfor %}
        {% endif %}

        <label class="fileContainer" style="margin-top:20px;" ondragover="dragOver(event,this)" ondragleave="leaveDrop(this)" ondrop="onDrop(event,this)">
          <div style="overflow:hidden;text-align:center;">
            <div class="dragDropIcon">
              <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-file-music" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M4 0h8a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2zm0 1a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H4z"/>
                <path fill-rule="evenodd" d="M10.304 3.13a1 1 0 0 1 1.196.98v1.8l-2.5.5v5.09c0 .495-.301.883-.662 1.123C7.974 12.866 7.499 13 7 13c-.5 0-.974-.134-1.338-.377-.36-.24-.662-.628-.662-1.123s.301-.883.662-1.123C6.026 10.134 6.501 10 7 10c.356 0 .7.068 1 .196V4.41a1 1 0 0 1 .804-.98l1.5-.3z"/>
              </svg>
            </div>
            <div class="fileContainerFileName fileName" ondrop="onDrop(event)"><span style="color:rgb(73,80,87);">Drag and drop an audio file here</span></div>
            <div class="fileContainerFileName fileNameDrop" ondrop="onDrop(event)" style="display:none;"><span style="color:rgb(73,80,87);">Drop it</span></div>
          </div>
          <input accept="audio/*" name="audio" id="id_audio" onchange="fileContainerChangeFile(event,this,'audio-clear_id')" style="margin-top:25px;" type="file"/>
        </label>

        {% if form.audio.errors %}
          {% for error in form.audio.errors %}
            <div class="invalid-feedback">
              {{ error }}
            </div>
          {% endfor %}
        {% endif %}

        <!-- If the form wasn't submitted earlier -->
        {% else %}

          <input name="title" type="text" id="id_title" value="{{ form.title.value|default_if_none:'' }}" placeholder="Title" style="margin-top:10px;">

          <textarea name="content" cols="40" rows="5" class="textarea" required="" id="id_content" value="" placeholder="Message (required)" style="margin-top:20px;">{{ form.content.value|default_if_none:'' }}</textarea>

          <input name="date_posted" type="text" id="id_date_posted" value="{{ form.date_posted.value|date:'Y-m-d G:i:s' }}" style="margin-top:20px;">

          <label class="fileContainer" style="margin-top:20px;" ondragover="dragOver(event,this)" ondragleave="leaveDrop(this)" ondrop="onDrop(event,this)">
            <div style="overflow:hidden;text-align:center;">
              <div class="dragDropIcon">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-card-image" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M14.5 3h-13a.5.5 0 0 0-.5.5v9c0 .013 0 .027.002.04V12l2.646-2.354a.5.5 0 0 1 .63-.062l2.66 1.773 3.71-3.71a.5.5 0 0 1 .577-.094L15 9.499V3.5a.5.5 0 0 0-.5-.5zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13zm4.502 3.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
                </svg>
              </div>
              <div class="fileContainerFileName fileName" ondrop="onDrop(event)"><span style="color:rgb(73,80,87);">Drag and drop an image here</span></div>
              <div class="fileContainerFileName fileNameDrop" ondrop="onDrop(event)" style="display:none;"><span style="color:rgb(73,80,87);">Drop it</span></div>
            </div>
            <input accept="image/*" name="image" id="id_image" onchange="fileContainerChangeFile(event,this,'image-clear_id')" style="margin-top:25px;" type="file"/>
          </label>

          <label class="fileContainer" style="margin-top:20px;" ondragover="dragOver(event,this)" ondragleave="leaveDrop(this)" ondrop="onDrop(event,this)">
            <div style="overflow:hidden;text-align:center;">
              <div class="dragDropIcon">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-file-music" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M4 0h8a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2zm0 1a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H4z"/>
                  <path fill-rule="evenodd" d="M10.304 3.13a1 1 0 0 1 1.196.98v1.8l-2.5.5v5.09c0 .495-.301.883-.662 1.123C7.974 12.866 7.499 13 7 13c-.5 0-.974-.134-1.338-.377-.36-.24-.662-.628-.662-1.123s.301-.883.662-1.123C6.026 10.134 6.501 10 7 10c.356 0 .7.068 1 .196V4.41a1 1 0 0 1 .804-.98l1.5-.3z"/>
                </svg>
              </div>
              <div class="fileContainerFileName fileName" ondrop="onDrop(event)"><span style="color:rgb(73,80,87);">Drag and drop an audio file here</span></div>
              <div class="fileContainerFileName fileNameDrop" ondrop="onDrop(event)" style="display:none;"><span style="color:rgb(73,80,87);">Drop it</span></div>
            </div>
            <input accept="audio/*" name="audio" id="id_audio" onchange="fileContainerChangeFile(event,this,'audio-clear_id')" style="margin-top:25px;" type="file"/>
          </label>

        {% endif %}

      </div>
      <button type="submit" class="button secondary_button short_button" style="margin-top:35px;margin-bottom:25px; background-color: silver;">Save</button>
      <!-- Returning non-field errors. -->
      {% if form.errors %}
        {% for error in form.non_field_errors %}
          <p>{{ error }}</p>
        {% endfor %}
      {% endif %}
    </form>
  </div>
</div>

<!-- Drag and drop functionality -->
<script src="{% static 'blog/js/drag-and-drop.js' %}"></script>

{% endblock content %}